feature:offline form submit
rtCamp/pwa-extension pull request #18
Opened 2020-01-06 17:15 UTC by sagarnasit

[x] Add service worker script for offline form submit.
[x] Modify template message for form submit.
[ ] Register plugin setting for form URLs.

2020-01-08 05:15 UTC, pradeep910 requested changes

2020-01-08 05:15 UTC, pradeep910 commented on inc/classes/class-admin-settings.php
> +							<input type="text" id="pwa_extension_form_urls" name="pwa_extension_form_urls" value="<?php echo esc_attr( get_option( 'pwa_extension_form_urls' ) ); ?>" />
@sagarnasit I think this should be text area so people can add URLs, each on new line.

2020-01-08 05:15 UTC, pradeep910 commented on js/offline-form.js
> +				// @todo This is duplicated with code in service-worker-navigation-routing.js.
Is this need to be removed? @chandrapatel

2020-01-08 05:15 UTC, pradeep910 commented on js/offline-form.js
> +				// @todo This is duplicated with code in service-worker-navigation-routing.js.
Need to update comment if not.

2020-01-08 08:34 UTC, chandrapatel requested changes

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +		add_option( 'pwa_extension_option_name', 'This is my option value.' );
Why do we need to add option here?

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +		add_options_page( 'PWA Extension Setting', 'PWA Extension Settings', 'manage_options', $this->page_slug, array( $this, 'options_page' ) );
Make labels translatable.

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +							<input type="text" id="pwa_extension_form_urls" name="pwa_extension_form_urls" value="<?php echo esc_attr( get_option( 'pwa_extension_form_urls' ) ); ?>" />
Also, register setting using `add_settings_field()`. Also add section to group settings using `add_settings_section()`.

https://developer.wordpress.org/plugins/settings/custom-settings-page/

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +							<input type="text" id="pwa_extension_form_urls" name="pwa_extension_form_urls" value="<?php echo esc_attr( get_option( 'pwa_extension_form_urls' ) ); ?>" />
So you don't' need to add additional markup like table, tr, td and all.

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +		register_setting( 'pwa_extension_group', 'pwa_extension_form_urls', array( $this, 'validate_setting' ) );
`pwa_extension_group` would be `$this->page_slug`

`pwa_extension_form_urls` would be `rt_pwa_extension_options` to save all the settings in single option name.

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +		register_setting( 'pwa_extension_group', 'pwa_extension_form_urls', array( $this, 'validate_setting' ) );
Third argument is an array type. https://developer.wordpress.org/reference/functions/register_setting/

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +			$message = __( 'Invalid Input', 'pwa-extension' );
An error message should be more informative. Add field label as well in message so user can identify, this error message for particular setting.

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +				esc_attr( 'settings_updated' ),
No need to escape static string.

2020-01-08 08:34 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +				esc_attr( 'settings_updated' ),
Second argument - `$code - (string) (Required) Slug-name to identify the error. Used as part of 'id' attribute in HTML output.`

2020-01-08 08:34 UTC, chandrapatel commented on js/offline-form.js
> +		"form"         : "Your form will be submitted once you are back online!"
These error message should be added in PHP and localize in JS and make strings translatable.

2020-01-08 08:34 UTC, chandrapatel commented on js/offline-form.js
> +				// @todo This is duplicated with code in service-worker-navigation-routing.js.
Let's keep this. It also in pwa plugin. If code updates in main plugin then we can update in our plugin.

2020-01-08 08:34 UTC, chandrapatel commented on js/offline-form.js
> +					console.log( 'errorText', errorText );
Remove console log

2020-01-08 14:00 UTC, sagarnasit commented
@chandrapatel I have addressed all the feedbacks.

2020-01-09 08:32 UTC, chandrapatel requested changes

2020-01-09 08:32 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +		printf( '<textarea name="rt_pwa_extension_options" rows="5">%1$s</textarea>', esc_html( $value ) );
Use `esc_textarea()`

2020-01-09 08:32 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +		printf( '<p><i>%1$s</i></p>', esc_html__( 'Use new line to separate multiple routes', 'pwa-extension' ) );
I think `Add separate multiple routes in new line` would be better?

2020-01-09 08:32 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +				<?php submit_button(); ?>
Use single `<?php ?>` tag for above functions calls.

2020-01-09 08:32 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +			$message = __( 'Invalid Form `Route`. Please enter valid form routes.', 'pwa-extension' );
Don't use tick. Use single or double quote.

2020-01-09 08:32 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +					__( 'White space are not allowed in `Form Routes`.', 'pwa-extension' ),
Don't use tick. Use single or double quote.

2020-01-09 08:32 UTC, chandrapatel commented on inc/classes/class-offline-form.php
> +			'form'          => __( 'Your form will be submitted once you are back online!', 'pwa-extension' ),
Better to escape these strings as well here because it will localize to JS file so.

2020-01-09 08:32 UTC, chandrapatel commented on inc/classes/class-offline-form.php
> +			// Remove `|` from end.
Don't use tick. Use single or double quote.

2020-01-09 08:35 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +		register_setting( $this->page_slug, 'rt_pwa_extension_options', array( $this, 'validate_setting' ) );
https://github.com/rtCamp/pwa-extension/pull/18#discussion_r364102084

This feedback is not addressed.

2020-01-09 09:27 UTC, sagarnasit commented
@chandrapatel Added my change with https://github.com/rtCamp/pwa-extension/pull/18#discussion_r364102084. `register_setting` takes an array as 3rd arg but we can also pass callable function as third arg. Both are valid.

2020-01-09 09:31 UTC, chandrapatel commented
> @chandrapatel Added my change with [#18 (comment)](https://github.com/rtCamp/pwa-extension/pull/18#discussion_r364102084). `register_setting` takes an array as 3rd arg but we can also pass callable function as third arg. Both are valid.

@sagarnasit Yup I know but that's for the backward compatibility so better to pass 3rd argument an array.

https://developer.wordpress.org/reference/functions/register_setting/

```php
// Back-compat: old sanitize callback is added.
    if ( is_callable( $args ) ) {
        $args = array(
            'sanitize_callback' => $args,
        );
    }
```

2020-01-09 13:41 UTC, chandrapatel commented on inc/classes/class-admin-settings.php
> +			'description'       => 'Form routes for offline form submission.',
@sagarnasit Please make this string translatable.

2020-01-09 13:41 UTC, chandrapatel submitted a review, later dismissed
@sagarnasit PR approved with minor feedback.

2020-01-21 12:28 UTC, merged

2020-01-21 12:54 UTC, pradeep910 commented
Reverting due to #21 issue.

2020-04-06 10:20 UTC, juhi123 commented
@deepaklalwani97 After deactivating PWA Extension plugin, form submission worked
With this plugin Gravity form is not working, please check https://juhi.dev5.rt.gw/contact-us/

2020-04-06 10:27 UTC, juhi123 commented
More Details:
WP Version: 5.4 and Active Theme 2017, Though tested with others too and it's not working
**Active Plugins:**
Gravity Forms Version 2.4.17.15
PWA Version 0.4.0
PWA Extension Develop Branch
iZooto browser push Version 3.6.6

![Screenshot 2020-04-06 at 3 56 01 PM](https://user-images.githubusercontent.com/8724401/78548964-3cf17d80-781f-11ea-9273-37aaf03f6176.png)