Feature/offline form support
rtCamp/pwa-extension pull request #28
Opened 2020-02-06 12:24 UTC by sagarnasit

Fixes: https://github.com/rtCamp/labs/issues/10

2020-02-14 07:30 UTC, deepaklalwani97 requested changes

2020-02-14 07:30 UTC, deepaklalwani97 commented on inc/classes/class-offline-form.php
> +		add_action( 'wp_front_service_worker', array( $this, 'offline_form_service_worker' ), 11 );
Is there any specific reason to use 11 priority here. If there is we should specify in a comment

2020-02-14 07:30 UTC, deepaklalwani97 commented on inc/classes/class-admin-settings.php
> +			'description'       => __( 'Form routes for offline form submission.', 'pwa-extension' ),
Use `esc_html__` instead of `__`

2020-02-14 07:30 UTC, deepaklalwani97 commented on inc/classes/class-admin-settings.php
> +		add_settings_section( 'pwa-extension-setting-options', __( 'Form Routes Options', 'pwa-extension' ), array( $this, 'callback_pwa_setting_section' ), 'options-general.php' );
Use `esc_html__` instead of `__`

2020-02-14 07:30 UTC, deepaklalwani97 commented on inc/classes/class-admin-settings.php
> +		add_settings_field( 'pwa-extension-routes-input', __( 'Form Routes', 'pwa-extension' ), array( $this, 'callback_url_input' ), 'options-general.php', 'pwa-extension-setting-options' );
Use `esc_html__` instead of `__`

2020-02-14 07:30 UTC, deepaklalwani97 commented on inc/classes/class-admin-settings.php
> +		add_options_page( __( 'PWA Extension Settings', 'pwa-extension' ), __( 'PWA Extension Settings', 'pwa-extension' ), 'manage_options', $this->page_slug, array( $this, 'options_page' ) );
Use `esc_html__` instead of `__`

2020-02-14 07:30 UTC, deepaklalwani97 commented on inc/classes/class-admin-settings.php
> +			$message = __( 'Invalid \'Form Route\'. Please enter valid form routes.', 'pwa-extension' );
Use `esc_html__` instead of `__`

2020-02-14 07:30 UTC, deepaklalwani97 commented on inc/classes/class-admin-settings.php
> +					__( 'White space are not allowed in \'Form Routes\'.', 'pwa-extension' ),
Use `esc_html__` instead of `__`

2020-02-26 11:14 UTC, sagarnasit commented
@deepaklalwani97 Added a few changes. Also haven't use `esc_html__` instead of `__` as all the places are static strings and do not need explicit escaping of Html.

2020-02-27 12:42 UTC, deepaklalwani97 commented
@sagarnasit When those static strings are translated the HTML content can be injected with translation text that's why we use `esc_html__` with static strings also.

2020-02-27 12:43 UTC, deepaklalwani97 approved these changes

2020-03-02 11:45 UTC, sagarnasit commented
@deepaklalwani97 Added escaping changes.

2020-03-04 10:28 UTC, merged